### ISSUE TITLE
Render a static HTML page of dashboard data

### ISSUE THREAD

**Issue by toolness** [18F/a11y-metrics#12]
It might be nice to render a static HTML page containing the same data as the CSV and publish it via Federalist. Benefits include:

* Hyperlinking project homepages
* Hyperlinking project repositories
* Highlighting rows that stand out in some way, such as projects that have no GitHub issues mentioning a11y (see #4)
* Adding explanatory information, such as those addressed by #7 and #8 
* Making the table sortable, for easier exploration of the data
* Embedding a graph that shows the change of data over time (see #6)

**Comment by nkkl** [comment]
Agreed. This will make it a lot easier for guild members and TTS-ers in general to act on the information aggregated. Let's keep it TTS-internal to start with.

**Comment by nkkl** [comment]
P1
* Hyperlinking project homepages
* Hyperlinking project repositories
* Highlighting rows that stand out in some way, such as projects that have no GitHub issues mentioning a11y (see #4)

P2
* Adding explanatory information, such as those addressed by #7 and #8

P3
* Making the table sortable, for easier exploration of the data
* Embedding a graph that shows the change of data over time (see #6) [graph vs. just a +/- indicator]

**Comment by toolness** [comment]
Cool! Oh, I forgot to mention that we should also hyperlink to the GitHub search results page for the a11y issues related to that repository, so folks can easily dig deeper.  Here's the URL to the a11y-related issues for CALC, for instance:

```
https://github.com/18F/calc/search?q=accessibility+OR+a11y&type=Issues
```

**Comment by toolness** [comment]
Just added this today w/ commits cc222d9d43c5437dbc3be6b5f01b740ab8158a28 through f36299f355c8de90d190263a6734b138e668beb2!  The static site is up at https://a11y.app.cloud.gov/.
